server:
  port: 8803
spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                pasword: guest
      bindings:
        input:
          destination: studyExchange
          content-type: application/json
          binder: defaultRabbit
          group: GGS
eureka:
  instance:
    prefer-ip-address: true
    instance-id: receive-8803.com
    lease-renewal-interval-in-seconds: 2  # 设置心跳的时间间隔(默认30秒)
    lease-expiration-duration-in-seconds: 5 # 连接超时时间,默认90秒
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka