server:
  port: 84
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        #默认8719端口,假如被占用会自动从8719依次+1,直到找到没有被占用的端口
        port: 8719
        # 配置sentinel dashboard地址
        dashboard: localhost:8080
# 消费者要去访问的微服务的名称
server-url:
  nacos-user-service: http://nacos-payment-provider
management:
  endpoints:
    web:
      exposure:
        include: "*"
