server:
  port: 8802
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit:  # 定义名称,用于与binding整合
          type: rabbit
          environment:  # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        input:  # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的Exchange的名称定义
          content-type: application/json  # 设置消息类型,本次为json,如果是文本则使用"text/plain"
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
#          group: GGS  # 分组,同类型微服务放到一个组中,竞争消费消息
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2  # 设置心跳的时间间隔(默认30秒)
    lease-expiration-duration-in-seconds: 5 # 连接超时时间,默认90秒
    instance-id: receive-8802.com # 在信息列表时显示主机名称
    prefer-ip-address: true # 访问路径标为ip地址